lesson #17
MaksymKutyshenko/qna-app pull request #15
Opened 2016-11-21 20:40 UTC by MaksymKutyshenko

2016-11-22 11:44 UTC, vkurennov requested changes

2016-11-22 11:44 UTC, vkurennov commented on app/controllers/concerns/subscribed.rb
> +module Subscribed
А зачем выносить в консерн? Подписка укладывается в парадигму ресурсов и заслуживает отдельного контроллера, вложенного в вопросы.

2016-11-22 11:44 UTC, vkurennov commented on app/controllers/concerns/subscribed.rb
> +module Subscribed
Да и к тому же, подписка есть только на вопросы, значит, выносить в консерн ее вообще смысла нет

2016-11-25 06:01 UTC, MaksymKutyshenko commented on app/controllers/concerns/subscribed.rb
> +module Subscribed
Поправил, спасибо.

2016-11-25 09:33 UTC, vkurennov approved these changes

2016-11-25 09:35 UTC, merged