lesson#7
MaksymKutyshenko/qna-app pull request #5
Opened 2016-09-18 19:30 UTC by MaksymKutyshenko

Реализованы задачи:
  - Только автор может отредактировать свой вопрос
  - Только автор может отредактировать свой ответ
  - Переделать удаление ответов на ajax
  - Автор вопроса может выбрать лучший ответ для своего вопроса (лучший ответ может быть только 1)
  - Автор вопроса может выбрать другой ответ как лучший, если у вопроса уже выбран лучший ответ.
  - Если у вопроса выбран лучший ответ, то он отображается первым в списке ответов.

2016-09-19 09:06 UTC, vkurennov commented on spec/acceptance/edit_answer_spec.rb
> +    scenario 'sees edit link' do
Сценарии на наличие ссылки, без взаимодействия с ней особого смысла не имеют. Во-первых, то что мы проверили наличеи ссылки ничего не доказывает, во-вторых, если у нас есть сценарий, где мы на эту ссылку кликаем, то и проверять ее наличие смысла нет, т.к. если ее нет на странице, то будет ошибка при попытке клика на нее. Т.е. мы ее и так неявно проверяем.

2016-09-19 09:07 UTC, vkurennov commented on spec/acceptance/edit_question_spec.rb
> +    scenario 'sees link Edit' do
И опять лишний сценарий. Смотри, хоть мы и используем слово "сценарий" как синоним теста, но на самом деле, это не синонимы. И "сценарий" используется для описания взаимодействия пользователя и системы и затем проверки результатов этого взаимодействия. Если у тебя сценарий состоит только из expect'a, чаще всего это означает, что либо сценарий неполный, либо уже есть более полная версия и этот сценарий лишний.

2016-09-19 09:10 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before {
Если в блоке более одной строки используй do ... end, фигруные скобки используются только для блоков-однострочников

2016-09-19 09:12 UTC, vkurennov commented on app/models/answer.rb
> +  def best!
А где же тест модели на этот метод? Нельзя просто взять и написать метод, сначала надо написать на него тесты :-)

2016-09-19 09:12 UTC, vkurennov requested changes
Исправь замечания

2016-09-19 09:12 UTC, vkurennov commented on app/models/answer.rb
> +    if best_answer.present?
Вот эти апдейты нужно обернуть в [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными.

2016-09-19 09:12 UTC, vkurennov commented on app/views/answers/best.js.erb
> +  $('.answers').html("<%= j render @answer.question.answers %>");
Не очень красивый вызов `@answer.question.answers`. Сделай в контроллере переменную @question и через нее вызывай.

2016-09-19 09:12 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +  $('.form-errors').html("<%= j render 'form_errors', errors: @answer.errors %>");
При удалении валидация не происходит, поэтому и ошибки валидации не может быть, а значит и проверка на нее лишняя. Не уадлиться объект может только если это было отменено в процессе выполнения коллбеков (before_destroy) или на уровне БД.

2016-09-19 09:12 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('.answers').html("<%= j render @answer.question.answers %>");
Тут надо обновлять конкретный ответ, а не рендерить заново все ответы.

2016-09-20 10:25 UTC, vkurennov commented on app/models/answer.rb
> +        best_answer.update(best: false)
Транзакция откатывается только в случае выброса исключения, поэтому внутри нее надо использовать только bang-версии update. Используй здесь `update!`

2016-09-20 10:27 UTC, vkurennov commented on spec/acceptance/best_answer_spec.rb
> +      expect(page).to have_content 'Best answer chosen'
Еще надо проверить, что лучший ответ стал первым

2016-09-20 10:27 UTC, vkurennov commented on spec/acceptance/best_answer_spec.rb
> +    scenario 'is trying to choose best answer to his question', js: true do
Нужен еще сценарий, когда юезр меняет уже существующий лучший ответ

2016-09-20 10:31 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    expect(answer1.best).to eq true
Т.к. для булевых атрибутов рельсы создают одноименный метод-предикат (в нашем случае best?), а rspec умеет динамически определять такие методы по названию матчера, то можно записывать так:
`expect(answer1).to be_best`

2016-09-20 10:31 UTC, vkurennov requested changes
Исправь замечания

2016-09-21 08:35 UTC, vkurennov commented on spec/acceptance/best_answer_spec.rb
> +        expect(page).to have_css(".answer:first-child", :text => answer.body)
Используй всегда один стиль записи хешей - новый.

2016-09-21 08:36 UTC, vkurennov commented on spec/acceptance/best_answer_spec.rb
> +    scenario 'is trying to choose already chosen best answer' do
Я другой сценарий имел в виду: у нас уже есть лучший ответ, но пользователь выбирает **другой** ответ лучшим. Старый становится обычным, а новый  - лучшим.

2016-09-21 08:36 UTC, vkurennov approved these changes
Принято, но сценарии допиши

2016-09-21 19:00 UTC, MaksymKutyshenko commented
Поправил. Спасибо за проверку!

2016-09-21 19:00 UTC, merged