lesson #9
MaksymKutyshenko/qna-app pull request #7
Opened 2016-10-14 03:10 UTC by MaksymKutyshenko

2016-10-14 10:25 UTC, vkurennov requested changes
Решение отличное, если бы не забыл тесты на консерн Votable в моделях. Придется дописать. Не должно быть методов в моделях, не покрытых тестами.

2016-10-14 10:25 UTC, vkurennov commented on app/models/concerns/votable.rb
> +module Votable
А где же тесты на все эти методы?

2016-10-14 18:24 UTC, MaksymKutyshenko commented
Поправил, спасибо.

2016-10-14 18:25 UTC, MaksymKutyshenko commented on app/models/concerns/votable.rb
> +module Votable
Поправил, спасибо.

2016-10-15 10:37 UTC, vkurennov approved these changes
Принято

2016-10-15 11:17 UTC, merged